#	Asignatura: Algoritmica
#	Trabajo: Práctica 4 - Programación Dinámica

PDTSP_exe : PDTSP.cpp
	g++ -Wall -std=c++17 -o $@ $<
PDTSP_BU_exe : PDTSP_BU.cpp
	g++ -Wall -std=c++17 -o $@ $<

codechefDP_exe: codechefDP.cpp
	g++ -Wall -std=c++17 -o $@ $<
