#	Asignatura: Algoritmica
#	Trabajo: Práctica 3 - Greedy

all: cercaniaTSP_exe insercionTSP_exe asignacionTareas_exe aristasTSP_exe

cercaniaTSP_exe : cercaniaTSP.cpp
	g++ -Wall -std=c++17 -o $@ $<

insercionTSP_exe : tsp_insercion.cpp
	g++ -Wall -std=c++17 -o $@ $<

asignacionTareas_exe : AsignacionTareas.cpp
	g++ -Wall -std=c++17 -o $@ $<

aristasTSP_exe : aristasTSP.cpp
	g++ -Wall -std=c++17 -o $@ $<
